### ISSUE TITLE
About problem scrobbling after 1%

### ISSUE THREAD

**Issue by Domi52** [tgwizard/sls#222] opened 2015-09-03 11:07 UTC
I checked "sony ericsson music player" and i think it works well, but this problem present in my favorite player "neutron music player"(last version from market), my android version 4.1.2, pls fix it, also i picked four stars

**Comment by HumbleBeeBumbleBee** [comment] 2016-01-02 18:06
Neutron Music Player is scrobbling after 1% of the song is played?

**Comment by inverse** [comment] 2016-01-03 13:51
What's the issue? Scrobbling after 1% listen?

**Comment by HumbleBeeBumbleBee** [comment] 2016-06-25 20:02
Hi @Domi52 if I can't recreate the problem there is nothing I can do. I will close this issue for now. Please share any more details and information if you can.
If the problem is fixed pleased let us know.

**Closed by HumbleBeeBumbleBee** 2016-06-25 20:02 UTC
Labels: bugs

**Comment by HumbleBeeBumbleBee** [comment] 2016-06-26 20:00
@Domi52
Neutron music player is not always the most reliable for scrobbling.
